### ISSUE TITLE
Error when setting API Key. Seems like it just hangs when trying to configure provider.

### ISSUE THREAD

**Issue by christian-stubberud** [arbs-io/vscode-openai#214]
It worked before, and then suddenly stopped working. Tried resetting the config, etc. I get an error when setting the API key. It seems like it just hangs when trying to configure the provider. Also, it shows 'Enter the openai.com API Key' even though I have chosen Azure OpenAI. Tested directly with curl, and this works fine.

![image](https://github.com/arbs-io/vscode-openai/assets/82025434/cd60d9e4-ec84-4b91-aa14-ea583dd58cb1)

**Comment by JorievSantvoort** [comment]
I have the same issue using the openai.azure.com variant. It used to be working fine.

The log output shows it tries to connect to api.openai.com instead of the azure instance URL while this is chosen in settings and using the setup the correct URL is provided.

To reproduce:
- Click the vscode-openai button in the bottom bar to setup.
- Click openai.azure.com:
![image](https://github.com/arbs-io/vscode-openai/assets/983506/f41b1ebd-ca0a-45da-80cf-5e00b1725b9f)

- Enter instance URL and press enter
![image](https://github.com/arbs-io/vscode-openai/assets/983506/fbfd4222-6c18-494e-90f6-2bedae986894)

- Enter instance Key, I noticed it says openai.com instead of azure
![image](https://github.com/arbs-io/vscode-openai/assets/983506/6c2086e4-0dc4-42a0-b2e7-d53136916c5a)

- After entering the process hangs, this is shown in the logs. after hitting Esc the incorrect API key shows up:

2024-01-19 13:44:16.398 [error]		Error: 500 status code (no body)
2024-01-19 13:44:16.399 [error]		TypeError: Cannot read properties of undefined (reading 'status')
2024-01-19 13:47:21.072 [error]		Error: 401 Incorrect API key provided: ********************. You can find your API key at https://platform.openai.com/account/api-keys.
2024-01-19 13:47:21.075 [info]		setting_configuration - event properties
{
  "vscode_version": "1.85.1",
  "vscode_ui_kind": "desktop",
  "vscode_language": "en",
  "extension_version": "1.5.7",
  "service_provider": "OpenAI",
  "host": "api.openai.com",
  "base_url": "https://api.openai.com/v1",
  "inference_model": "setup-required",
  "inference_deploy": "setup-required",
  "embeddings_model": "setup-required",
  "embeddings_deploy": "setup-required",
  "az_api_version": "2023-05-15"
}
2024-01-19 13:47:56.133 [error]		Error: 500 status code (no body)
2024-01-19 13:47:56.134 [error]		TypeError: Cannot read properties of undefined (reading 'status')

**Comment by arbs-io** [comment]
hi @JorievSantvoort 
sorry for the delayed response. i've changed country recently and that's taken up most of my time. 
Are you still having issues? could you run the "reset..." and re-try the setup. I can replicate the issue your having with any of the services.

**Comment by arbs-io** [comment]
Ok, thanks. There were some bug fixes in the previous release. Will close the issue. But let me know if there are any other issues
