### ISSUE TITLE
Chat does not use model selected

### ISSUE THREAD

**Issue by L03TJ3** [arbs-io/vscode-openai#237]
Maybe I am looking in the wrong place.
I have set up my connection with openai API.
filled in my key.
Selected model (latest gpt-4-2024-04-09, but also tried the gpt-4-turbo-preview, same result)
Selected embeddings (ada)

I don't think the model is being used in the chat?
Is the model used for chat configurable?

(Image got cut of on vscode, but was the same question as on chat.openai)
![image](https://github.com/arbs-io/vscode-openai/assets/6606028/f498365f-8ea7-4410-9970-a3e94d0b490b)

**Comment by arbs-io** [comment]
You're not doing anything wrong. I see the same results using the model. I suspect the model trained on recent data, but the Formula 1 data didn't cut. 

From reading around, I see that this model is "better" at many tasks. But I need help seeing something that contains more recent information. So, I suspect/believe this version is just an improvement over the previous one rather than an increase in knowledge capacity. 

![image](https://github.com/arbs-io/vscode-openai/assets/71968891/e9e3c3df-56e9-4b28-8a21-6d4f8de51d11)
