### ISSUE TITLE
Openai api key

### ISSUE THREAD

**Issue by benoitm974** [arbs-io/vscode-openai#253]
Using chatgpt api key, tried chatgpt4, 4-turboi, 4o and the ada or small embedded text. I get to un predictable behavior.

At start it works amazingly well, I can start a blank project in VS, prompt my idea and I get some code. Then I can add all or part of the code to the query resources, and it is likely to work or suddenly only answer:
"That's not a valid question." or "I couldn't find the answer to that question in your files."

Do you have an idea about any setup fine tuning to avoid this ? the log output don't show any error model and api key are ok, changng the model doesn't help either....

**Comment by arbs-io** [comment]
Hi @benoitm974 
The problem with embedding is compatibility. If OpenAI force an update on version you most likely need to re-embedded the resources. With out having more details it hard to tell. But I suspect you initially use standard ada embedded v1, which is now v2. The issue is the compatibility between then. So when you ask a question the embedded values miss matching. 

Could you remove and re embedded a resource

**Comment by benoitm974** [comment]
H thanks for your response, I'm using ada embedded v2 since the begining. I tried removing and adding the file back it does not help. This issue can occur within 20 minutes after first generation works well and then suddenly stop..

**Comment by arbs-io** [comment]
Hi @benoitm974 
I verified the issue, but it's occurring for Azure and Openai and is happening on the backend services, not the extension. I can't resolve the issue but will report to openai and microsoft
